export const productActionTypes={
FETCHING_START:"FETCHING_START",
FETCHING_SUCCESS:"FETCHING_SUCCESS",
FETCHING_ERROR:"FETCHING_ERROR",
Add_TO_CART:"Add_TO_CART",
Add_TO_Wishlist:"Add_TO_Wishlist",

}